/*
   Monday, February 11, 2002 9:46:13 AM
   User: 
   Server: ANDY-MPECR6VC86\VSTE
   Database: simpleSpy
   Application: 
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
CREATE TABLE dbo.Table1
	(
	AgentID int NOT NULL,
	CodeName char(20) NULL,
	Specialty char(10) NULL,
	Language char(10) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Table1 ADD CONSTRAINT
	PK_Table1 PRIMARY KEY CLUSTERED 
	(
	AgentID
	) ON [PRIMARY]

GO
COMMIT
