//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3328.4
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace SpyMaster {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class asDataSet : DataSet {
        
        private Agent_SpecDataTable tableAgent_Spec;
        
        public asDataSet() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected asDataSet(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Agent_Spec"] != null)) {
                    this.Tables.Add(new Agent_SpecDataTable(ds.Tables["Agent_Spec"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Agent_SpecDataTable Agent_Spec {
            get {
                return this.tableAgent_Spec;
            }
        }
        
        public override DataSet Clone() {
            asDataSet cln = ((asDataSet)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Agent_Spec"] != null)) {
                this.Tables.Add(new Agent_SpecDataTable(ds.Tables["Agent_Spec"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableAgent_Spec = ((Agent_SpecDataTable)(this.Tables["Agent_Spec"]));
            if ((this.tableAgent_Spec != null)) {
                this.tableAgent_Spec.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "asDataSet";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/asDataSet.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableAgent_Spec = new Agent_SpecDataTable();
            this.Tables.Add(this.tableAgent_Spec);
        }
        
        private bool ShouldSerializeAgent_Spec() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void Agent_SpecRowChangeEventHandler(object sender, Agent_SpecRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class Agent_SpecDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnCodeName;
            
            private DataColumn columnSpecialtyname;
            
            internal Agent_SpecDataTable() : 
                    base("Agent_Spec") {
                this.InitClass();
            }
            
            internal Agent_SpecDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn CodeNameColumn {
                get {
                    return this.columnCodeName;
                }
            }
            
            internal DataColumn SpecialtynameColumn {
                get {
                    return this.columnSpecialtyname;
                }
            }
            
            public Agent_SpecRow this[int index] {
                get {
                    return ((Agent_SpecRow)(this.Rows[index]));
                }
            }
            
            public event Agent_SpecRowChangeEventHandler Agent_SpecRowChanged;
            
            public event Agent_SpecRowChangeEventHandler Agent_SpecRowChanging;
            
            public event Agent_SpecRowChangeEventHandler Agent_SpecRowDeleted;
            
            public event Agent_SpecRowChangeEventHandler Agent_SpecRowDeleting;
            
            public void AddAgent_SpecRow(Agent_SpecRow row) {
                this.Rows.Add(row);
            }
            
            public Agent_SpecRow AddAgent_SpecRow(string CodeName, string Specialtyname) {
                Agent_SpecRow rowAgent_SpecRow = ((Agent_SpecRow)(this.NewRow()));
                rowAgent_SpecRow.ItemArray = new object[] {
                        CodeName,
                        Specialtyname};
                this.Rows.Add(rowAgent_SpecRow);
                return rowAgent_SpecRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                Agent_SpecDataTable cln = ((Agent_SpecDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            internal void InitVars() {
                this.columnCodeName = this.Columns["CodeName"];
                this.columnSpecialtyname = this.Columns["Specialtyname"];
            }
            
            private void InitClass() {
                this.columnCodeName = new DataColumn("CodeName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCodeName);
                this.columnSpecialtyname = new DataColumn("Specialtyname", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSpecialtyname);
                this.columnSpecialtyname.AllowDBNull = false;
            }
            
            public Agent_SpecRow NewAgent_SpecRow() {
                return ((Agent_SpecRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new Agent_SpecRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(Agent_SpecRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Agent_SpecRowChanged != null)) {
                    this.Agent_SpecRowChanged(this, new Agent_SpecRowChangeEvent(((Agent_SpecRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Agent_SpecRowChanging != null)) {
                    this.Agent_SpecRowChanging(this, new Agent_SpecRowChangeEvent(((Agent_SpecRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Agent_SpecRowDeleted != null)) {
                    this.Agent_SpecRowDeleted(this, new Agent_SpecRowChangeEvent(((Agent_SpecRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Agent_SpecRowDeleting != null)) {
                    this.Agent_SpecRowDeleting(this, new Agent_SpecRowChangeEvent(((Agent_SpecRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveAgent_SpecRow(Agent_SpecRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class Agent_SpecRow : DataRow {
            
            private Agent_SpecDataTable tableAgent_Spec;
            
            internal Agent_SpecRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableAgent_Spec = ((Agent_SpecDataTable)(this.Table));
            }
            
            public string CodeName {
                get {
                    try {
                        return ((string)(this[this.tableAgent_Spec.CodeNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAgent_Spec.CodeNameColumn] = value;
                }
            }
            
            public string Specialtyname {
                get {
                    return ((string)(this[this.tableAgent_Spec.SpecialtynameColumn]));
                }
                set {
                    this[this.tableAgent_Spec.SpecialtynameColumn] = value;
                }
            }
            
            public bool IsCodeNameNull() {
                return this.IsNull(this.tableAgent_Spec.CodeNameColumn);
            }
            
            public void SetCodeNameNull() {
                this[this.tableAgent_Spec.CodeNameColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class Agent_SpecRowChangeEvent : EventArgs {
            
            private Agent_SpecRow eventRow;
            
            private DataRowAction eventAction;
            
            public Agent_SpecRowChangeEvent(Agent_SpecRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public Agent_SpecRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
